### PR TITLE
Improvements to yes_you_want_a_build_step.md ( first paragraph)

### PR DESCRIPTION
**Pull request by human154**

### CODE REVIEW

**Comment by bencroker** [comment]
Your effort is appreciated, but this PR is too small in nature and you’ve created at least 10 other such PRs. Please create one single PR will all language changes and I’ll happily review it all in one go.

**Comment by human154** [comment]
To be honest I guess I'm not really willing to put that much more work into it. (sorry)  I'm just a guy who was reading your documentation for the first time, and noticed a bunch of glaring issues with the wording.  

To be clear, I'd be more than willing to do that with future pull requests. I'm just not willing to rework the work I've done already,

**Comment by human154** [comment]
...or maybe what you're asking for is really not that difficult (i.e. transforming my multiple pull requests into one) and that actually just seems like extra work to me because I have no  real understanding of git or github yet. 😁   

I accept the challenge... Let me see what I can do.😁

**Comment by bencroker** [comment]
> To be honest I guess I'm not really willing to put that much more work into it. (sorry) I'm just a guy who was reading your documentation for the first time, and noticed a bunch of glaring issues with the wording.

That’s legit, and again thank you for the effort. The docs, as I’m sure you’ve noticed, need a fair amount of work, which is planned. While your PRs are valid, going through over 10 PRs is also a lot of work. If you want to contribute to this open source project, then by all means do. I was requesting that you merge all your PRs into one PR so that I can go through the suggestions all together when reworking the docs.

> ...or maybe what you're asking for is really not that difficult (i.e. transforming my multiple pull requests into one) 

Yes, that was it.

**Pull request closed without merging**
