### PR TITLE
Rewrite docs

### PR DESCRIPTION
**Pull request by bencroker**
Full rewrite and restructuring of the going deeper and reference docs.

### CODE REVIEW

**Comment by bencroker** [comment]
@delaneyj can you please set up redirects from the following pages to `/reference/attribute_plugins` to maintain SEO?

- `/reference/plugins_core`
- `/reference/plugins_dom`
- `/reference/plugins_browser`
- `/reference/plugins_backend`
- `/reference/plugins_logic`

**Comment by bencroker** [comment]
@delaneyj please be sure to check out this page before approving: https://github.com/starfederation/datastar/pull/367/files#diff-b92a5e1d433b5269b6a62067bc8e66e8bc4a1b52b040fad0e3fd537639a4c6e8

**Comment by delaneyj** [comment]
You should be able to do `document.body` without assigning to an element first, but I'm good either way

**Comment by bencroker** [comment]
Removed the element assignment. Just waiting on your 301 redirect magic now! (add to this PR, please)

**Comment by bencroker** [comment]
@delaneyj please check out the new “Going Deeper” page and set up redirects to `/guide/going_deeper` from the following pages:

- `/guide/go_deeper`
- `/guide/howl`
- `/guide/batteries_included`
- `/guide/streaming_backend`

**Comment by bencroker** [comment]
@delaney please help me by adding to the things to look out for, under “Unlearning”.

**Pull request merged**
