### PR TITLE
Serve bundles as static files in C# example

### PR DESCRIPTION
**Pull request by erizet**
I had to serve the bundles folder to make the csharp example work.

### CODE REVIEW

**Comment by bencroker** [comment]
@SpiralOSS can you please take a look?

**Comment by bencroker** [comment]
Does https://github.com/starfederation/datastar/pull/364 resolve this?

**Comment by SpiralOSS** [comment]
It should. I was building the .js myself and forgot to point back at the repo after testing.

**Comment by bencroker** [comment]
Great, thanks!

**Pull request closed without merging**
