### PR TITLE
Remove merge options covered by idiomorph

### PR DESCRIPTION
**Pull request by potatotech**
Use cases for `inner`, `outer`, and `upsert_attributes` can all be handled by `morph` and signals.

### CODE REVIEW

**Comment by bencroker** [comment]
Can you please explain?

**Comment by delaneyj** [comment]
@potatotech  upsert_attributes isn't covered by idiomorph

**Comment by potatotech** [comment]
Restored `upsert_attributes`

**Comment by delaneyj** [comment]
Needs to be removed from `datastar.go` and any examples as well but getting close!

**Comment by bencroker** [comment]
I think I’ve changed all instances in all examples now.

**Comment by bencroker** [comment]
`main` has been merged, fyi.

**Comment by delaneyj** [comment]
LGTM will put off until v20 release

**Comment by bencroker** [comment]
> Use cases for `inner`, `outer`, and `upsert_attributes` can all be handled by `morph` and signals.

@potatotech can you please help me understand how `inner` can be handled when the default morph style used is `outerHTML`, which is not currently configurable in Datastar?

**Comment by bencroker** [comment]
If it turns out that the only redundant merge strategy is `outer`, then I’d opt for leaving it in, as it still offers the benefit of allowing you to target an element by selector without requiring matching IDs.

**Comment by bencroker** [comment]
I’ve come to the strong conclusion that there is no upside whatsoever in removing merge options. Even `outer` can be useful considering that the back-end should have full control over deciding what DOM elements to swap. Without it, an ID must already exist in the front-end. I vote _not_ to merge.

**Comment by potatotech** [comment]
The backend *is* the frontend with hypermedia. If there's a missing id, add it in the template. When swapping fragments, datastar needs to target a specific element, and the only unique selector is id. Morph is sufficient because all other selectors are less specific\*.

\* There are things like `#id[attribute]` or `#id.class`, but id is already unique, so these are not necessary. You definitely should not be using them to store state either.

**Comment by delaneyj** [comment]
I'm going to leave it @potatotech, while I :100: agree you should always use the idiomorph I can see value in the effiency of inner/outerhtml for sheer speed in certain situatins.  Thank you for your effort!

**Pull request closed without merging**
