### PR TITLE
sdk/dotnet nuget

### PR DESCRIPTION
**Pull request by SpiralOSS**
Requirements:

Secret Keys:
- NUGET_PACKAGE_TOKEN - a Token (classic) generated in GitHub that has access to write, read, and delete packages
- NUGET_API_KEY - an API key made at nuget.org

Variables:
- DOTNET_SDK_ROOT = sdk/dotnet/src
- FS_PROJ_PATH = sdk/dotnet/src/Datastar.fsproj
- USERNAME = starfederation

Other:
- Check the triggers in the YAML. Right now it is waiting on `release`. Let me know what you would prefer.
- `${{steps.gitversion.outputs.CommitsSinceVersionSource}}` is what was suggested for the published version. It came out looking like this: https://www.nuget.org/packages/SpiralOSS.Datastar/

### CODE REVIEW

**Comment by bencroker** [comment]
How do you suggest sharing those keys? If you can get them to me, I can add to GitHub secrets.

You might want to add `workflow_dispatch` as the trigger, instead of `release`, so you can run the action manually, since presumably, the versioning is independent of library releases.

**Comment by SpiralOSS** [comment]
NUGET_PACKAGE_TOKEN:
There's six steps under "Automating Package Generation with GitHub Actions" for making the token.
https://medium.com/@jammelimohamedyassin/deploying-your-own-nuget-packages-to-github-nuget-registry-using-github-actions-cbec07f10fbc

NUGET_API_KEY:
I was assuming that one of the owners of StarFederation would create a nuget account; the first section of this site is creating the key:
https://www.jamescroft.co.uk/how-to-build-publish-nuget-packages-with-github-actions/

I will change the trigger soon-ish.

**Comment by bencroker** [comment]
I’ve swapped `NUGET_PACKAGE_TOKEN` with `GITHUB_TOKEN`, which should already work.

I’ve created an organisation for `starfederation` and added a `NUGET_API_KEY` to secrets.

I’ve replaced the variables with hard-coded values (to avoid unnecessary setup)

I’ve updated the action to use `workflow_dispatch`.

Is there anything else you need?

**Comment by SpiralOSS** [comment]
Thank you! I was just coming on here to say that I probably wouldn't be able to make any changes until this evening, which will be 5+ hours.

The only last thing is there is an 'if' condition in the release section that should probably be deleted (line 49).

**Comment by bencroker** [comment]
Ok, I’ll let you take care of that and any remaining loose ends.

**Comment by SpiralOSS** [comment]
I think it's all set, @bencroker

**Comment by bencroker** [comment]
Thanks! Requesting a review from @khalwat, as he’s our GitHub actions gatekeeper.

**Comment by SpiralOSS** [comment]
Paging Dr. @khalwat

**Comment by khalwat** [comment]
Looks good to me. Release the hounds.

**Review by khalwat — APPROVED** [review]
Looks good, thanks!

**Comment by bencroker** [comment]
Merged and submitted!

> This package has not been published yet. It will appear in search results and will be available for install/restore after both validation and indexing are complete. Package validation and indexing may take up to an hour.

**Comment by bencroker** [comment]
Here it is: https://www.nuget.org/packages/StarFederation.Datastar/

**Pull request merged**
