### PR TITLE
reference/sse: clarify retry behavior

### PR DESCRIPTION
**Pull request by magiconair**
* document initial wait time
* provide an example for "infinite" retries

### CODE REVIEW

**Comment by bencroker** [comment]
> The initial wait time is `1s`.

I find this comment confusing rather than clarifying. The initial wait time is `retryScaler` multiplied by `retryMaxWaitMs`, which happens to be 1 second given their default values, which are documented.

> Use a large number (e.g. `Number.MAX_SAFE_INTEGER`) for "infinite" retries.

Does this really need to be stated? Definitely not “infinite”.

**Comment by magiconair** [comment]
I was looking in the documentation for these two values: What does the backoff algorithm start with and how can I turn off the retry limit since I want a constant, predictable, infinite retry for the '/event' endpoint for screens where there is no user to hit F5. I cannot afford the screen to stall.

Initial retry time: Is this better? The default is not on the page. Probably in the code only.

As for disabling the retry limit: I think a sentinel value or a separate flag to disable the limit makes the intent more clear (and maybe less error-prone than `data-on-load="sse('/events', {retryScaler:1,retryMaxCount:Number.MAX_SAFE_INTEGER})"`. #382 says that using `Number.MAX_SAFE_INTEGER` achieves virtually the same thing. It is logical but not obvious - at least not to me.

**Comment by bencroker** [comment]
I know you mean well but I find the contributions misleading more than providing any real value. The “initial wait time” is not 1 second! It is a function of two settings.

**Comment by bencroker** [comment]
So after looking into this a bit more, I realised that I misunderstood, and that the retry interval is hard-coded to be 1 second. I’ve created a PR to make this configurable in https://github.com/starfederation/datastar/pull/393. Apologies for my misunderstanding.

**Pull request closed without merging**
