### PR TITLE
Road to v1 essay

### PR DESCRIPTION
**Pull request by delaneyj**

### CODE REVIEW

**Comment by bencroker** [comment]
This reads great! I might make a few edits if that’s ok, but otherwise you said it all in a concise and clear way.

**Comment by bencroker** [comment]
Maybe mentioning tooling (VSCode extension and JetBrains plugin) after the SDKs?

**Comment by delaneyj** [comment]
> Maybe mentioning tooling (VSCode extension and JetBrains plugin) after the SDKs?

:100: I thought I did!

> I might make a few edits if that’s ok

yes please do, add anything else you think of

**Comment by pepe** [comment]
Please apologize for being off-topic, but I was nodding a lot when reading this essay. I started to experiment with Datastar just before these rewrites, and I also needed to fix it for the new version. But frankly, it made me understand the "system" a lot more.

If you are interested, I can write a small testimony. My previous "modus vivendi" was HTMX + Hyperscript + SSE, so I can compare approaches. I am using Janet programming language with my own backend framework.

**Comment by delaneyj** [comment]
Honestly I need this kind of content @pepe as contributions more than code. Building Datastar has been pretty easy, even with the rewrites.  Teaching and adoption is where I need the most help!

**Pull request merged**
