### PR TITLE
BSD support and better taskfile formatting

### PR DESCRIPTION
**Pull request by Superpat**
The way the yaml is formatted was pretty confusing to me, this way feels more natural to read.

### CODE REVIEW

**Comment by bencroker** [comment]
The current format follows the convention specified in the docs, so I’m not sure if it makes sense to deviate from them.
https://taskfile.dev/usage/#platform-specific-tasks-and-commands

screenshot-qUV1CSWK@2x

**Comment by Superpat** [comment]
Guh, that's annoying. The problem is the docs themselves arent terribly consistent; 

Here platform is before it's related commands:
```
tasks:
  build-windows-amd64:
    platforms: [windows/amd64]
    cmds:
      - echo 'Running command on Windows (amd64)'
```
      
And here 
```

tasks:
  build:
    cmds:
      - cmd: echo 'Running command on Windows (amd64) and macOS'
        platforms: [windows/amd64, darwin]
      - cmd: echo 'Running on all platforms'
```
it's the opposite..

Hence why my eyes had a lot of trouble parsing it. Maybe I should take this up on their repo..

**Comment by bencroker** [comment]
If you can verify that your way indeed works, I can merge as I agree it is clearer to read.

**Comment by Superpat** [comment]
Well I ran it, so I can confirm it works. I'm also adding bsd support based on this branch and it works fine.

**Comment by bencroker** [comment]
Can you add your BSD changes and I'll merge?

**Comment by Superpat** [comment]
Yeah, still need to figure out how to get tailwind to work properly, but I'm close

**Comment by Superpat** [comment]
It's done. It should work on all BSD systems, since I dont know of any that dont support pnpm.

**Comment by Superpat** [comment]
Ah damn just noticed something wrong with the file, suprised running task worked

**Comment by Superpat** [comment]
Fixed

**Comment by bencroker** [comment]
Perfect, thanks!

**Pull request merged**
